apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdfConverterPubSub-deployment
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pdfConverterPubSub
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pdfConverterPubSub
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: pdfConverterPubSub
        image: gcr.io/{{ .Values.pullImagefrom }}/disearch/pdf-convertor-pubsub:1.0.55
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.pdfConverterPubSub.containerPort }}

