apiVersion: v1
kind: Service
metadata:
  name: text2speech-service
  namespace: {{ .Values.namespace | default "default" }}
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    app: text2speech
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.text2speech.containerPort }}
  type: LoadBalancer

