apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbotAskAngie-deployment
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chatbotAskAngie
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: chatbotAskAngie
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: chatbotAskAngie
        image: gcr.io/{{ .Values.pullImagefrom }}/disearch/chatbot-askangie:1.0.55
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.chatbotAskAngie.containerPort }}

