apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdfHighlighter-deployment
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pdfHighlighter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pdfHighlighter
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: pdfHighlighter
        image: gcr.io/{{ .Values.pullImagefrom }}/disearch/pdf-highlighter:{{ .Values.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.pdfHighlighter.containerPort }}

