apiVersion: apps/v1
kind: Deployment
metadata:
  name: diProjectServices-deployment
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: diProjectServices
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: diProjectServices
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: diProjectServices
        image: gcr.io/{{ .Values.pullImagefrom }}/disearch/diproject-services:{{ .Values.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.diProjectServices.containerPort }}

