apiVersion: v1
kind: Service
metadata:
  name: diProjectServices-service
  namespace: {{ .Values.namespace | default "default" }}
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    app: diProjectServices
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.diProjectServices.containerPort }}
  type: LoadBalancer

