apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiModelDocChat-deployment
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: multiModelDocChat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: multiModelDocChat
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: multiModelDocChat
        image: gcr.io/{{ .Values.pullImagefrom }}/disearch/multi-model-doc-chat:1.0.55
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.multiModelDocChat.containerPort }}

