apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadataProcessingPubSub-deployment
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: metadataProcessingPubSub
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: metadataProcessingPubSub
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: metadataProcessingPubSub
        image: gcr.io/{{ .Values.pullImagefrom }}/disearch/metadata-process-pubsub:1.0.55
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.metadataProcessingPubSub.containerPort }}

