apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdfConverter-deployment
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pdfConverter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pdfConverter
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: pdfConverter
        image: gcr.io/{{ .Values.pullImagefrom }}/disearch/pdf-converter:{{ .Values.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.pdfConverter.containerPort }}
