apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentStatus-deployment
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: documentStatus
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: documentStatus
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: documentStatus
        image: gcr.io/{{ .Values.pullImagefrom }}/disearch/document-status:{{ .Values.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.documentStatus.containerPort }}

