apiVersion: v1
kind: Service
metadata:
  name: metadataExtractor-service
  namespace: {{ .Values.namespace | default "default" }}
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    app: metadataExtractor
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.metadataExtractor.containerPort }}
  type: LoadBalancer

