apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    app: disearch
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.containerPort }}
  type: LoadBalancer
