apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-convert-deployment
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: 6
  selector:
    matchLabels:
      app: pdf-convert
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pdf-convert
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: pdf-convert
        image: gcr.io/{{ .Values.pullImagefrom }}/disearch/pdf-converter:{{ .Values.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.pdfConvert.containerPort }}
        
