apiVersion: apps/v1
kind: Deployment
metadata:
  name: researchAgent-deployment
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: researchAgent
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: researchAgent
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: researchAgent
        image: gcr.io/{{ .Values.pullImagefrom }}/disearch/research-agent:{{ .Values.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.researchAgent.containerPort }}

