apiVersion: v1
kind: Service
metadata:
  name: researchAgent-service
  namespace: {{ .Values.namespace | default "default" }}
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    app: researchAgent
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.researchAgent.containerPort }}
  type: LoadBalancer

