apiVersion: apps/v1
kind: Deployment
metadata:
  name: diToolClassifier-deployment
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: diToolClassifier
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: diToolClassifier
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: diToolClassifier
        image: gcr.io/{{ .Values.pullImagefrom }}/disearch/tool-classifier:1.0.55
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.toolClassifier.containerPort }}

