## This file will hold the actual values for the Helm chart. These values will either come from the default values defined in schema.yaml or the user input provided during installation (as in the mpdev command)
replicaCount: 1
pullImagefrom: "aretecinc-public" 
## Client GCP Project ID (Example: my-project)
projectID: ""  
#tag: 1.0.8
namespace: "default"

pdfConvert:
  containerPort: 5000 
  ## Connection string for postgress database. (Must be base64 encoded)
  cloudSqlDbConn: ""

loadbalancer:
  containerPort: 8080
  ## Kube API Server Internal Endpoint URL. For Example: https://10.8.8.8:6446
  k8sApiServerUrl: ""
  # ETCD Host must be in base64 encoded form. Example Value: etcd.default.svc.cluster.local:2379
  etcdHost: "ZXRjZC5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjIzNzk="
  etcdPassword: ""
   
docChat:
  containerPort: 5000

vertexAiFollowup:
  containerPort: 8000

vertexaiCitation:
  containerPort: 8000

vertexai:
  containerPort: 5000
  openaiApiKey: ""
  statusCloudFn: ""
  imageSummaryCloudFn: ""
  updateMetadataFn: ""
  schema: "disearch_search"

vertexaiSummary:
  containerPort: 8000

serviceAccountName: "gke-sa"


        


